export const apiPaths = {
  placesSearch: '/api/places/search',
  placesReverse: '/api/places/reverse',
  poiAroundRoute: '/api/poi/around-route',
  route: '/api/route',
  loop: '/api/loop',
  exportGpx: '/api/export/gpx',
  valhallaStatus: '/api/valhalla/status',
  valhallaUpdateStart: '/api/valhalla/update/start',
  cloudProviders: '/api/cloud/providers',
  cloudSession: '/api/cloud/session',
  cloudStatus: '/api/cloud/status',
  cloudOAuthStart: '/api/cloud/oauth/start',
  cloudOAuthCallback: '/api/cloud/oauth/callback',
  cloudDisconnect: '/api/cloud/disconnect',
  cloudBackupUpload: '/api/cloud/backup/upload',
  cloudBackupRestore: '/api/cloud/backup/restore',
  feedback: '/api/feedback',
} as const
