export type OsmLabel = {
  fr: string
  en: string
}

export const osmTagLabels: Record<string, OsmLabel> = {
  name: { fr: 'Nom', en: 'Name' },
  'name:fr': { fr: 'Nom (FR)', en: 'Name (FR)' },
  'name:en': { fr: 'Nom (EN)', en: 'Name (EN)' },
  brand: { fr: 'Marque', en: 'Brand' },
  operator: { fr: 'Exploitant', en: 'Operator' },
  tourism: { fr: 'Tourisme', en: 'Tourism' },
  historic: { fr: 'Historique', en: 'Historic' },
  natural: { fr: 'Nature', en: 'Natural' },
  leisure: { fr: 'Loisir', en: 'Leisure' },
  sport: { fr: 'Sport', en: 'Sport' },
  cuisine: { fr: 'Cuisine', en: 'Cuisine' },
  amenity: { fr: 'Service', en: 'Amenity' },
  shop: { fr: 'Commerce', en: 'Shop' },
  access: { fr: 'Accès', en: 'Access' },
  surface: { fr: 'Revêtement', en: 'Surface' },
  fee: { fr: 'Payant', en: 'Fee' },
  capacity: { fr: 'Capacité', en: 'Capacity' },
  internet_access: { fr: 'Accès internet', en: 'Internet access' },
  bicycle_parking: { fr: 'Stationnement vélo', en: 'Bicycle parking' },
  description: { fr: 'Description', en: 'Description' },
  wikipedia: { fr: 'Wikipédia', en: 'Wikipedia' },
  wikidata: { fr: 'Wikidata', en: 'Wikidata' },
  opening_hours: { fr: 'Horaires', en: 'Opening hours' },
  website: { fr: 'Site web', en: 'Website' },
  'contact:website': { fr: 'Site web', en: 'Website' },
  phone: { fr: 'Téléphone', en: 'Phone' },
  'contact:phone': { fr: 'Téléphone', en: 'Phone' },
  email: { fr: 'Email', en: 'Email' },
  wheelchair: { fr: 'Accessibilité PMR', en: 'Wheelchair access' },
  leaf_cycle: { fr: 'Cycle foliaire', en: 'Leaf cycle' },
  leaf_type: { fr: 'Type de feuilles', en: 'Leaf type' },
  'addr:street': { fr: 'Rue', en: 'Street' },
  'addr:housenumber': { fr: 'Numéro', en: 'House number' },
  'addr:postcode': { fr: 'Code postal', en: 'Postal code' },
  'addr:city': { fr: 'Ville', en: 'City' },
}

export const osmValueLabels: Record<string, OsmLabel> = {
  wood: { fr: 'bois', en: 'wood' },
  forest: { fr: 'forêt', en: 'forest' },
  deciduous: { fr: 'caduc', en: 'deciduous' },
  evergreen: { fr: 'persistant', en: 'evergreen' },
  mixed: { fr: 'mixte', en: 'mixed' },
  broadleaved: { fr: 'feuillu', en: 'broadleaved' },
  needleleaved: { fr: 'résineux', en: 'needleleaved' },
  meadow: { fr: 'prairie', en: 'meadow' },
  scrub: { fr: 'broussailles', en: 'scrub' },
  grassland: { fr: 'pelouse', en: 'grassland' },
  heath: { fr: 'lande', en: 'heath' },
  wetland: { fr: 'zone humide', en: 'wetland' },
  attraction: { fr: 'attraction', en: 'attraction' },
  museum: { fr: 'musée', en: 'museum' },
  monument: { fr: 'monument', en: 'monument' },
  memorial: { fr: 'mémorial', en: 'memorial' },
  castle: { fr: 'château', en: 'castle' },
  ruins: { fr: 'ruines', en: 'ruins' },
  archaeological_site: { fr: 'site archéologique', en: 'archaeological site' },
  fort: { fr: 'fort', en: 'fort' },
  place_of_worship: { fr: 'lieu de culte', en: 'place of worship' },
  viewpoint: { fr: 'point de vue', en: 'viewpoint' },
  peak: { fr: 'sommet', en: 'peak' },
  waterfall: { fr: 'cascade', en: 'waterfall' },
  beach: { fr: 'plage', en: 'beach' },
  bay: { fr: 'baie', en: 'bay' },
  spring: { fr: 'source', en: 'spring' },
  cave: { fr: 'grotte', en: 'cave' },
  cliff: { fr: 'falaise', en: 'cliff' },
  information: { fr: 'information', en: 'information' },
  hostel: { fr: 'auberge', en: 'hostel' },
  hotel: { fr: 'hôtel', en: 'hotel' },
  guest_house: { fr: 'chambre d’hôtes', en: 'guest house' },
  picnic_site: { fr: 'aire de pique-nique', en: 'picnic site' },
  camp_site: { fr: 'camping', en: 'camp site' },
  bicycle: { fr: 'vélo', en: 'bicycle' },
  supermarket: { fr: 'supermarché', en: 'supermarket' },
  bakery: { fr: 'boulangerie', en: 'bakery' },
  convenience: { fr: 'supérette', en: 'convenience store' },
  farm: { fr: 'ferme', en: 'farm' },
  outdoor: { fr: 'plein air', en: 'outdoor' },
  sports: { fr: 'sport', en: 'sports' },
  marketplace: { fr: 'marché', en: 'marketplace' },
  bicycle_repair_station: { fr: 'station de réparation vélo', en: 'bicycle repair station' },
  bicycle_parking: { fr: 'parking vélo', en: 'bicycle parking' },
  rental: { fr: 'location', en: 'rental' },
  cafe: { fr: 'café', en: 'cafe' },
  restaurant: { fr: 'restaurant', en: 'restaurant' },
  fast_food: { fr: 'restauration rapide', en: 'fast food' },
  pub: { fr: 'pub', en: 'pub' },
  bar: { fr: 'bar', en: 'bar' },
  toilets: { fr: 'toilettes', en: 'toilets' },
  pharmacy: { fr: 'pharmacie', en: 'pharmacy' },
  drinking_water: { fr: 'eau potable', en: 'drinking water' },
  shelter: { fr: 'abri', en: 'shelter' },
  fuel: { fr: 'carburant', en: 'fuel' },
  bank: { fr: 'banque', en: 'bank' },
  atm: { fr: 'distributeur', en: 'ATM' },
  parking: { fr: 'parking', en: 'parking' },
  charging_station: { fr: 'borne de recharge', en: 'charging station' },
  public: { fr: 'public', en: 'public' },
  private: { fr: 'privé', en: 'private' },
  designated: { fr: 'aménagé', en: 'designated' },
  permissive: { fr: 'toléré', en: 'permissive' },
  customers: { fr: 'clients', en: 'customers' },
  residents: { fr: 'résidents', en: 'residents' },
  paved: { fr: 'revêtu', en: 'paved' },
  unpaved: { fr: 'non revêtu', en: 'unpaved' },
  asphalt: { fr: 'asphalte', en: 'asphalt' },
  concrete: { fr: 'béton', en: 'concrete' },
  gravel: { fr: 'gravier', en: 'gravel' },
  compacted: { fr: 'compacté', en: 'compacted' },
  ground: { fr: 'terre', en: 'ground' },
  dirt: { fr: 'terre battue', en: 'dirt' },
  sand: { fr: 'sable', en: 'sand' },
  cobblestone: { fr: 'pavés', en: 'cobblestone' },
  pebbles: { fr: 'galets', en: 'pebbles' },
  grass: { fr: 'herbe', en: 'grass' },
  unknown: { fr: 'inconnu', en: 'unknown' },
  yes: { fr: 'oui', en: 'yes' },
  no: { fr: 'non', en: 'no' },
  limited: { fr: 'limité', en: 'limited' },
  customers_only: { fr: 'clients uniquement', en: 'customers only' },
}
