export const apiPaths = {
  placesSearch: '/api/v1/places/search',
  placesReverse: '/api/v1/places/reverse',
  poiAroundRoute: '/api/v1/poi/around-route',
  route: '/api/v1/route',
  loop: '/api/v1/loop',
  exportGpx: '/api/v1/export/gpx',
  health: '/api/v1/health',
  valhallaStatus: '/api/v1/valhalla/status',
  valhallaUpdateStart: '/api/v1/valhalla/update/start',
  cloudProviders: '/api/v1/cloud/providers',
  cloudSession: '/api/v1/cloud/session',
  cloudStatus: '/api/v1/cloud/status',
  cloudOAuthStart: '/api/v1/cloud/oauth/start',
  cloudOAuthCallback: '/api/v1/cloud/oauth/callback',
  cloudDisconnect: '/api/v1/cloud/disconnect',
  cloudBackupUpload: '/api/v1/cloud/backup/upload',
  cloudBackupRestore: '/api/v1/cloud/backup/restore',
  feedback: '/api/v1/feedback',
} as const
